# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33dd2e2f0ec1f851474311822dda982f3593679104df76a5c7137587833b0367651c52b36c4dc00f7149aee759acf0e7758aa3efec0efca13ecd929ebfc133f2

test:
  secret_key_base: 104a1ba8dd987a156a3e6b8bd716b08eb3ed6cde278e89238654c6f1fbe83c6e8de9b2ce081d237c67b724951f075e8ff409f5e390d5f28e0109987908649d84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
